place = input("Enter a place: ")
animal = input("Enter a animal:")
job = input("Enter the name of a job:")
badsmell = input("Enter a bad smell:")
print(f"We went to {place} to see a {animal} but a {job}er said go away. I said why? They said you smell like {badsmell}")
