place = input("Enter a place: ")
animal = input("Enter a animal:")
job = input("Enter the name of a job:")
badsmell = input("Enter a bad smell:")
print("We went to "+place)
print("To see a "+animal)
print("But a "+job)
print("Said go away")
print("So I said why?")
print("They said because you smell like "+badsmell)